name: Validate Helm output

on:
  push:
    paths:
      - "helm/charts/**"
      - "helm/tests/**"
  pull_request:
    paths:
      - "helm/charts/**"
      - "helm/tests/**"

jobs:
  validate-helm-input:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cases:
          - name: Complete successful deployment (global)
            id: "global"
          - name: Complete successful deployment (individual)
            id: "individual"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.11.1"

      - name: ${{ matrix.cases.name }}
        shell: bash
        run: cd ./helm/tests/scripts && bash 02_test_helm_outputs.sh --case ${{ matrix.cases.id }}
